apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: istio
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: false
  generators:
  - matrix:
      generators:
      - clusters:
          selector:
            matchLabels:
              environment: 'hub'          
      - git:
          repoURL: '{{metadata.annotations.istio_repo_url}}'
          revision: '{{metadata.annotations.istio_repo_revision}}'
          directories:
            - path: '{{metadata.annotations.istio_repo_basepath}}'      

  template:
    metadata:
      name: 'istio-{{path.basename}}'
      labels:
        environment: '{{metadata.labels.environment}}'
    spec:
      project: default
      source:
        repoURL: '{{metadata.annotations.istio_repo_url}}'
        path: '{{path}}'
        targetRevision: '{{metadata.annotations.istio_repo_revision}}'
      destination:
        name: '{{name}}'
      syncPolicy:
        automated:
          allowEmpty: true
        retry:
          backoff:
            duration: 1m
          limit: 100
        syncOptions:
          - CreateNamespace=true
