apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-eastwestgateway
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-eastwest
  project: default
  source:
    chart: gateway
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: ${ISTIO_VERSION}
    helm:
      values: |
        # Name allows overriding the release name. Generally this should not be set
        name: "istio-eastwestgateway-${REVISION}"
        # revision declares which revision this gateway is a part of
        revision: "${REVISION}"
        replicaCount: 1
        service:
          # Type of service. Set to "None" to disable the service entirely
          type: LoadBalancer
          ports:
            # Port for health checks on path /healthz/ready.
            # For AWS ELBs, this port must be listed first.
            - port: 15021
              targetPort: 15021
              name: status-port
            # Port for multicluster mTLS passthrough; required for Gloo Mesh east/west routing
            - port: 15443
              targetPort: 15443
              # Gloo Mesh looks for this default name 'tls' on a gateway
              name: tls
            # Port required for VM onboarding
            #- port: 15012
              #targetPort: 15012
              # Required for VM onboarding discovery address
              #name: tls-istiod
          annotations:
            # AWS NLB Annotation
            service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
          loadBalancerIP: ""
          loadBalancerSourceRanges: []
          externalTrafficPolicy: ""
        # Pod environment variables
        env: {}
        annotations:
          proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
        # Labels to apply to all resources
        labels:
          # Set a unique label for the gateway so that virtual gateways
          # can select this workload.
          app: istio-eastwestgateway-${REVISION}
          istio: eastwestgateway
          revision: ${REVISION}
          # Matches spec.values.global.network in the istiod deployment
          topology.istio.io/network: ${CLUSTER_NAME}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true