apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  project: default
  source:
    chart: istiod
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.22.1
    helm:
#      values: |
#        revision: ${REVISION}
#        global:
#          meshID: mesh1
#          multiCluster:
#            clusterName: hub-cluster
#          network: network1
#          hub: docker.io/istio
#          tag: 1.22.1
#        meshConfig:
#          trustDomain: hub-cluster
#          accessLogFile: /dev/stdout
#          accessLogEncoding: JSON
#          enableAutoMtls: true
#          defaultConfig:
#            # Wait for the istio-proxy to start before starting application pods
#            holdApplicationUntilProxyStarts: true
#            envoyAccessLogService:
#              address: gloo-mesh-agent.gloo-mesh:9977
#            proxyMetadata:
#              ISTIO_META_DNS_CAPTURE: "true"
#              ISTIO_META_DNS_AUTO_ALLOCATE: "true"
#        pilot:
#          env:
#            PILOT_ENABLE_K8S_SELECT_WORKLOAD_ENTRIES: "false"
#            PILOT_SKIP_VALIDATE_TRUST_DOMAIN: "true"
#            PILOT_ENABLE_WORKLOAD_ENTRY_AUTOREGISTRATION: "true"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    #automated: {}
  ignoreDifferences:
  - group: '*'
    kind: '*'
    managedFieldsManagers:
    - argocd-application-controller